### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by hirenshah** [lantongxue/rustdesk-api-server-pro#13]
Any chance you can provide a Docker Compose example please?

**Comment by lantongxue** [comment]
See the docker deployment method

**Comment by innovara** [comment]
Without environment variables for admin user and password:
```
services:
  rustdesk-api-server-pro:
    container_name: rustdesk-api-server-pro
    image: ghcr.io/lantongxue/rustdesk-api-server-pro:latest
    volumes:
      - ./server.yaml:/app/server.yaml
    network_mode: host
    restart: unless-stopped
```
With environment variables:
```
services:
  rustdesk-api-server-pro:
    container_name: rustdesk-api-server-pro
    image: ghcr.io/lantongxue/rustdesk-api-server-pro:latest
    environment:
      - "ADMIN_USER=youruser"
      - "ADMIN_PASS=yourpassword"
    volumes:
      - ./server.yaml:/app/server.yaml
    network_mode: host
    restart: unless-stopped
```
Please note that in this example `server.yaml` and the compose file are in the same directory. You'd need to adjust the first part of the volume if that's not the case.
